"""empty message

Revision ID: 4e6efd754489
Revises: 
Create Date: 2024-11-01 14:45:54.301068

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4e6efd754489"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "estents",
        sa.Column("eid", sa.String(length=64), nullable=False),
        sa.Column("sid", sa.String(length=32), nullable=False),
        sa.Column("wid", sa.String(length=30), nullable=False),
        sa.Column("stype", sa.String(length=8), nullable=False),
        sa.Column("iso", sa.String(length=32), nullable=False),
        sa.Column("pid", sa.String(length=32), nullable=True),
        sa.Column("children", postgresql.JSON(astext_type=Text()), nullable=True),
        sa.Column("civ", sa.String(length=4), nullable=True),
        sa.Column("name", sa.String(length=32), nullable=True),
        sa.Column("stats", postgresql.JSON(astext_type=Text()), nullable=True),
        sa.Column("items", postgresql.JSON(astext_type=Text()), nullable=True),
        sa.Column("talents", postgresql.JSON(astext_type=Text()), nullable=True),
        sa.Column("data", postgresql.JSON(astext_type=Text()), nullable=True),
        sa.ForeignKeyConstraint(["iso"], ["estents.sid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pid"], ["estents.sid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wid"], ["estents.sid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("eid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("estents")
    # ### end Alembic commands ###
