[project]
name = "httpapi"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbobo",
    "fastapi>=0.117.1",
    "httpx>=0.28.1",
    "pydantic>=2.11.9",
    "pydantic-settings>=2.11.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "python-multipart>=0.0.20",
    "ujson>=5.11.0",
    "uvicorn>=0.37.0",
]

[project.optional-dependencies]
aws = [
    "botocore>=1.40.50",
]

[tool.uv.sources]
dbobo = { path = "../dbobo", editable = true }
