reload = true
verify_email_template = 'Dave1VerificationTpl'
workers_count = 1

[DB]
database = 'hellas'
dsn = 'sqlite+aiosqlite:///{database}.db'
#dsn = 'postgresql+asyncpg://DoboApi:DoboApi@localhost:5432/{database}'

[OAuth]
algorithm = "RS512"
issuer = ''
audience = 'gh'

